Create some new options for `BFSIterator`
JuliaGraphs/Graphs.jl pull request #389
Opened 2024-06-26 19:49 UTC by Tortar

Solves https://github.com/JuliaGraphs/Graphs.jl/issues/288.

This PR adds 2 new options, which can be useful when iterating in BFS:

- `depth_limit`: specify the maximum level at which BFS should stop beforehand.
- `neighbor_func`: specify which function to use when iterating in BFS, e.g. sometimes using `inneighbors` could be useful and this allows that

2024-07-12 23:44 UTC, Tortar commented
Bump, I have some use cases for this, it should be easy to review

2024-09-25 16:23 UTC, gdalle requested changes
Sorry for the delay, don't hesitate to ping like you did

2024-09-26 01:22 UTC, Tortar commented on src/iterators/bfs.jl
> +which will stop the search after it is reached and a `neighbors_type` which specifies
should be better now

2024-09-26 01:24 UTC, Tortar commented on test/iterators/bfs.jl
> +    nodes_visited = collect(BFSIterator(g2, [8, 1, 6]; depth_limit=1))
it should be implied by the fact that `sort(nodes_visited[4:end]) == sort(levels[2])`

2024-09-26 01:27 UTC, Tortar commented
let me know if you have more review suggestions @gdalle and thank you for taking a look

2024-09-28 10:44 UTC, Tortar commented
Let me know if there is still something to address @gdalle

2024-09-28 10:45 UTC, Tortar commented
If you could release a new version with this I would be grateful so that I can use it

2024-09-28 11:20 UTC, gdalle approved these changes
thanks! I'll tag a release

2024-09-28 11:20 UTC, merged